/**
 * @file subjectDepartments.ts
 * OSU subject code → Rate My Professors department keyword(s).
 *
 * Why this exists: RMP profiles are matched to instructors by name, and same-name
 * collisions are disambiguated by checking a candidate's RMP `department` against
 * the course's subject (see selectBestRmpMatch). A bare prefix check ("SOCIOL" →
 * "Sociology") covers many subjects, but OSU has ~200 subject codes and RMP uses
 * its own department vocabulary, so the two often diverge:
 *   - abbreviations that aren't prefixes:  BUSML  → "Marketing" / "Business"
 *   - different names for the same field:   KINESIO → "Physical Education"
 *                                           THEATRE → "Theater" (RMP spelling)
 *   - many fine-grained codes roll up:      ESxxx, TLxxx → "Education"
 *
 * Each value is a list of NORMALIZED (lowercase, letters-only) keywords; a
 * candidate matches when its normalized RMP department and a keyword are equal or
 * one is a prefix of the other (min 3 chars) — see departmentMatchesSubject.
 *
 * Source of truth: codes harvested from OSU's live class API (content.osu.edu),
 * keywords grounded in real RMP department strings sampled for OSU (school 724).
 * Keys are normalized subject codes. Subjects whose code already prefixes their
 * RMP department (e.g. SOCIOL, MATH, CHEM, PSYCH) are intentionally omitted — the
 * generic prefix check in departmentMatchesSubject handles them.
 */

export const SUBJECT_DEPARTMENT_KEYWORDS: Readonly<
  Record<string, readonly string[]>
> = {
  accad: ['art', 'design'],
  acctmis: ['accounting', 'business'],
  aedecon: ['agriculture', 'economics'],
  aeroeng: ['aerospace', 'engineering'],
  afamast: ['african', 'africanamerican'],
  agrcomm: ['agriculture'],
  agsysmt: ['agriculture'],
  airsci: ['military'],
  animsci: ['animal'],
  artssci: ['artssciences'],
  asamsts: ['ethnic', 'international'],
  ase: ['agriculture'],
  asl: ['americansign'],
  atmossc: ['earth', 'geography'],
  aviatn: ['aviation'],
  bcs: ['languages', 'slavic'],
  bioethc: ['philosophy'],
  biomede: ['biomedical', 'engineering'],
  biomsci: ['biology', 'molecular'],
  biophrm: ['biochemistry', 'pharmacology'],
  busadm: ['business'],
  busfin: ['business', 'finance'],
  busmhr: ['business', 'humanresources', 'management'],
  busml: ['business', 'marketing'],
  busoba: ['business', 'management'],
  cbe: ['chemicalengineering', 'engineering'],
  cbg: ['biology', 'molecular'],
  chemphy: ['chemistry', 'physics'],
  civicll: ['leadership', 'public'],
  civilen: ['civil', 'engineering'],
  comldr: ['agriculture'],
  compstd: ['comparative'],
  consci: ['consumer'],
  consysm: ['construction'],
  crplan: ['landscape', 'public'],
  cscffs: ['consumer'],
  cse: ['computerscience'],
  csfrst: ['consumer', 'textiles'],
  cshspmg: ['consumer', 'hospitality'],
  cybrsec: ['computerscience', 'engineering'],
  czech: ['languages', 'slavic'],
  denthyg: ['allied'],
  dsablst: ['ethnic'],
  eall: ['eastasian', 'languages'],
  ece: ['computerscience', 'electrical', 'engineering'],
  educst: ['education'],
  edutl: ['education', 'teaching'],
  eeob: ['biology', 'molecular'],
  ehe: ['education'],
  engr: ['engineering'],
  engredu: ['engineering'],
  engrtec: ['engineering'],
  enr: ['environ', 'naturalresources'],
  entmlgy: ['entomology'],
  enveng: ['engineering', 'environ'],
  esce: ['education'],
  eseadm: ['education'],
  esepol: ['education'],
  esepsy: ['education'],
  eshesa: ['education'],
  esltech: ['education'],
  esphe: ['education'],
  esqrem: ['education'],
  esqual: ['education'],
  essped: ['education'],
  esspsy: ['education'],
  eswde: ['education'],
  ethnstd: ['ethnic'],
  fabeng: ['agricultural', 'engineering'],
  faes: ['agriculture'],
  fdscte: ['food'],
  filmstd: ['film'],
  frit: ['french', 'italian'],
  gened: ['education'],
  hcinnov: ['health', 'publichealth'],
  hcs: ['agriculture', 'horticulture'],
  hdfs: ['humandev', 'humandevelopment'],
  hindi: ['languages'],
  histart: ['arthistory'],
  hthrhsc: ['allied', 'health'],
  humnntr: ['nutrition'],
  hw: ['health', 'physicaleducation'],
  intmed: ['medicine'],
  intstds: ['international'],
  ise: ['engineering', 'industrial'],
  islam: ['neareastern', 'religious'],
  japanse: ['japanese', 'languages'],
  jewshst: ['history', 'religious'],
  kinesio: ['athletic', 'physicaleducation'],
  knhes: ['health', 'physicaleducation'],
  knpe: ['physicaleducation'],
  knsfhp: ['physicaleducation'],
  knsism: ['physicaleducation'],
  larch: ['landscape'],
  mba: ['business'],
  mcr: ['medicine'],
  mdrngrk: ['greek', 'languages'],
  meatsci: ['agriculture', 'animal'],
  mecheng: ['engineering', 'mechanical'],
  medcoll: ['medicine'],
  medlbs: ['allied', 'medicine'],
  medmcim: ['medicine', 'microbiology'],
  medren: ['comparative', 'history'],
  micrbio: ['microbiology'],
  milsci: ['military'],
  molgen: ['biology', 'molecular'],
  mse: ['engineering', 'materials'],
  mvngimg: ['art', 'film'],
  navalsc: ['military'],
  nelc: ['languages', 'neareastern'],
  neuro: ['neuroscience'],
  nrsadvn: ['nursing'],
  nrsprct: ['nursing'],
  nuclren: ['engineering', 'nuclear'],
  peds: ['medicine'],
  persian: ['languages'],
  phr: ['pharmacy'],
  physio: ['physiology'],
  plntpth: ['agriculture', 'biology'],
  politsc: ['political'],
  portgse: ['portuguese'],
  pubafrs: ['public'],
  pubhbio: ['biostatistics', 'publichealth'],
  pubhehs: ['publichealth'],
  pubhepi: ['publichealth'],
  pubhhbp: ['publichealth'],
  pubhhmp: ['health', 'publichealth'],
  pubhlth: ['publichealth'],
  quechua: ['languages'],
  radsci: ['allied', 'radiological'],
  relstds: ['religion', 'religious'],
  respthr: ['allied'],
  romania: ['languages'],
  rurlsoc: ['agriculture', 'sociology'],
  sasia: ['international', 'languages'],
  scandvn: ['languages'],
  socwork: ['socialwork'],
  somali: ['languages'],
  sphhrng: ['speech'],
  swahili: ['languages'],
  swedish: ['languages'],
  theatre: ['theater', 'theatre'],
  tlcte: ['education', 'teaching'],
  tled: ['education', 'teaching'],
  tlielp: ['education', 'teaching'],
  tlistem: ['education', 'teaching'],
  tlted: ['education', 'teaching'],
  turkish: ['languages'],
  ukrain: ['languages', 'slavic'],
  urdu: ['languages'],
  vetbios: ['anatomy', 'veterinary'],
  vetclin: ['veterinary'],
  vetprev: ['veterinary'],
  vissci: ['optometry', 'vision'],
  weldeng: ['engineering', 'welding'],
  wgsst: ['women', 'womens'],
  yiddish: ['languages'],
};
